### ISSUE TITLE
A problem about filter single select

### ISSUE THREAD

**Issue by dandan-xu** [imoutsatsos/uno-choice-plugin#11]
When i follow the example，I found when i press backspace。The single select input will become the first element of array。not the default value i set。also the 'disabled'  param that should not have been selected becomes param can choose。

I think this is not as expected，I suggest that filtering should only be responsible for filtering the options in the drop-down box. The input box always displays the set default value or the first element of the array and let the user choose which one they want.
or maybe i did something wrong？please teach me what should i do，thanks
<img src="https://github.com/dandan-xu/20191117-/blob/master/1.png" />
<img src="https://github.com/dandan-xu/20191117-/blob/master/2.png" />

**Comment by kinow** [comment]
Hi @dandan-xu 

This repository is only where we started the project. It lives now under the [jenkinsci org](https://github.com/jenkinsci/active-choices-plugin/), and issues are tracked with [JIRA](https://issues.jenkins-ci.org/).

For questions, you might have more luck using StackOverflow: https://stackoverflow.com/search?q=active+choices+plugin

**Comment by kinow** [comment]
@imoutsatsos what do you think of disabling issues on this repo? That can be done using the settings menu :point_up:
